### ISSUE TITLE
Error calling get annotation web service

### ISSUE THREAD

**Issue by dungscout96** [hed-standard/hed-matlab#25]
When calling hed.getHedAnnotations providing EEGLAB EEG.event and HED sidecar string, an error received below
```matlab
>> hed.getHedAnnotations(EEG.event, EEG.etc.HED)
78              p = inputParser;
Error using HedToolsService/getHedAnnotations
Error AttributeError: [AttributeError: 'NoneType' object has no attribute 'HED']
```

The EEGLAB file is attached
[eeglab_sample_file.zip](https://github.com/user-attachments/files/16380623/eeglab_sample_file.zip)

**Comment by VisLab** [comment]
@dungscout96 This EEG.event structure does not have an `onset` field, which is required.  You must use the `rectify_events` function before.  Here is the correct code:

```matlab
hed1 = getHedTools('8.3.0', 'https://hedtools.org/hed');
eventsRect = rectify_events(EEG.event, EEG.srate);
issues = hed1.validateEvents(eventsRect, EEG.etc.HED);
annots = hed1.getHedAnnotations(eventsRect, EEG.etc.HED);
```

Be sure to download the latest version of hed-matlab.  If you are using the Python version, make sure that hedtools 0.5.0 or later is being used.

**Comment by dungscout96** [comment]
Thanks Kay, this fixed it!
