### ISSUE TITLE
Error calling validate sidecar service

### ISSUE THREAD

**Issue by dungscout96** [hed-standard/hed-matlab#26]
See command history below. I also attached the `hed_json` matlab variable.
[hed_json.mat.zip](https://github.com/user-attachments/files/16381431/hed_json.mat.zip)

<img width="738" alt="image" src="https://github.com/user-attachments/assets/8b252672-69e9-4fdb-aea1-cc16f4b49f0c">

**Comment by VisLab** [comment]
@dungscout96 I don't know why this didn't work for you. Make sure that you download the latest version of hed-matlab.  What version of MATLAB are you running? I tried it on R2023B and it worked fine with hed_json.  

Here is the code that I used:

```matlab
hed1 = getHedTools('8.3.0', 'https://hedtools.org/hed');
issues = hed1.validateSidecar(hed_json);
```

**Comment by dungscout96** [comment]
There might be some fixes to the server with recent updates. It's working now!
